spring:
  profiles:
    active: dev
  application:
    name: book.network
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  port: 8085
  servlet:
    context-path: /api/v1/



